CREATE DATABASE ABD_03361_A_RITA_CAGIANO;

USE ABD_03361_A_RITA_CAGIANO;



INSERT INTO COMIDAS_FAVORITAS (NOME, COMIDA, CATEGORIA_COMIDA, NOTA_QUALIDADE, CIDADE) VALUES ('CARLA', 'lasanha', 'massas', 9, 'São Paulo')

INSERT INTO COMIDAS_FAVORITAS (NOME, COMIDA, CATEGORIA_COMIDA, NOTA_QUALIDADE, CIDADE)
VALUES
('Lucia', 'baião de dois', 'comida nordestina', 9, 'Fortaleza'),
('Camila', 'macarronada', 'comida italiana', 10, 'São Paulo'),
('Carlos', 'yakisoba', 'comida chinesa', 9, 'São Paulo'),
('Rita', 'pizza', 'comida italiana', 10, 'São paulo');

-- SELECIONE TODAS AS COMIDAS COM NOTA MAIOR QUE 8:
SELECT * FROM COMIDAS_FAVORITAS WHERE NOTA_QUALIDADE > 8;

-- MOSTRE APENAS O NOME DAS PESSOAS E SUAS COMIDAS FAVORITAS DO TIPO DOCE ORDENADAS PELO NOME

SELECT * FROM COMIDAS_FAVORITAS


-- NOME_PESSOA COMIDA TIPO NOTA CIDADE


